version: '3.7'

services:
  web:
    build: ./app
    command: ./entrypoint.sh run
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hn
      - POSTGRES_PASSWORD=hn
      - POSTGRES_DB=hn
  celery:
    env_file:
      - ./.env.dev
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    command: celery -A hn worker -l debug
    depends_on:
      - db
      - redis
  celery-beat:
    env_file:
      - ./.env.dev
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    command: celery -A hn beat -l debug
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
volumes:
  postgres_data:
