version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: ./entrypoint.sh run
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web
  celery:
    env_file:
      - ./.env.prod
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    command: celery -A hn worker -l info
    depends_on:
      - db
      - redis
  celery-beat:
    env_file:
      - ./.env.prod
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    command: celery -A hn beat -l info
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
volumes:
  postgres_data:
  static_volume: