# Generated by Django 3.0.1 on 2019-12-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField(unique=True, verbose_name='story id')),
                ('title', models.CharField(max_length=255, verbose_name='story title')),
                ('url', models.URLField(max_length=255, verbose_name='story url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='story created')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
